# 7. Conclusão

Esta auditoria de acompanhamento inaugura uma metodologia que tem por objetivo tornar a fiscalização dos RPPS mais eficiente. Acredita-se que o acompanhamento que se pretende realizar nos RPPS permitirá gerar subsídios suficientes para que a orientação deste Tribunal em relação ao aperfeiçoamento das análises dos RPPS nos processos de contas de governo de município possa ser atendida de forma satisfatória.  

O relatório evidencia uma situação bastante preocupante, a exigir do Tribunal de Contas uma atuação mais perene junto aos RPPS. A atuação do TCE-RJ mediante as atividades de auditoria e análise de contas deve dar-se de forma a que uma subsidie e complemente a outra.

Com relação ao Certificado de Regularidade Previdenciária, na data de 01.12.2017, mais da metade dos entes estavam com o CRP vencido, irregular, portanto. Destes, 45,45% com o CRP vencido há mais de um ano. Para estes entes, todos da esfera municipal, isso implica, em tese, no não recebimento de transferências voluntárias da União nem o recebimento de Compensação Previdenciária, além de outras restrições que podem impactar as finanças municipais de forma bastante significativa.

Destaque-se que alguns entes municípais tiveram seus CRP emitidos por decisão judicial.

Quanto ao encaminhamento dos demonstrativos (DRAA, DAIR, DIPR e DPIN) ao Ministério da Previdência, a situação não é melhor. Muitos municípios estão com pendência, indicando claramente problemas administrativos que precisam ser equacionados.

Com relação ao DAIR, foram identificados 48 RPPS que apresentaram o enquadramento de Fundos de Investimento divergente do enquadramento proposto pelo Ministério da Fazenda. Foram identificados 16 RPPS que extrapolaram os limites de investimento definidos na Resolução CMN nº 9.922/10.

Considerando as peculiaridades desta auditoria e o fato deste ser o primeiro relatório produzido com a metodologia descrita, a qual ainda está em desenvolvimento, será proposto que os responsáveis sejam cientificados das impropriedades verificadas, das quais lhes serão dada ciência mediante o encaminhamento a cada RPPS de sua **Ficha de Apuração de Inconsistências - RPPS**, documento que constitui o Anexo 2 a este relatório de auditoria. 


Em face do exposto e examinado, sugere-se: 

**I** - **Ciência** deste relatório de auditoria à SSR;

**II** - **Expedição de ofício** para o encaminhamento de cópia deste relatório à Secretaria de Políticas de Previdência Social do  Ministério da Fazenda.

**III** - **Ciência** ao titular do RPPS e ao responsável pelo controle interno do Ente da **Ficha de Apuração de Inconsistências - RPPS** que constitui o Anexo 2 deste relatório para que promovam as correções das impropriedades encontradas ou apresentem a este Tribunal, pelo email **`rpps@tce.rj.gov.br`**, as considerações que entenderem pertinentes acerca dos pontos contidos no referido documento.    

**IV** - O **arquivamento** do processo.

